using AutoMapper;
using RedBubble.Application.DTOs;
using RedBubble.Application.DTOs.Order;
using RedBubble.Application.DTOs.OrderItem;
using RedBubble.Domain.Entities.Models.Orders;
using RedBubble.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace RedBubble.Application.Mappers
{
    public class OrderProfile : Profile
    {
        public OrderProfile()
        {
            // convert from CreateOrderDTO to Order
            CreateMap<CreateOrderDTO, Order>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Generated by DB
                .ForMember(dest => dest.Status, opt => opt.Ignore()) // Set default in service
                .ForMember(dest => dest.OrderDate, opt => opt.Ignore()) // Set in service
                .ForMember(dest => dest.CustomerId, opt => opt.Ignore()) // From logged-in user
                .ForMember(dest => dest.Customer, opt => opt.Ignore()) // Avoid circular refs
                .ForMember(dest => dest.ShippingAddress, opt => opt.MapFrom(src => new Address(
                    "", // FirstName - not provided in DTO
                    "", // LastName - not provided in DTO
                    src.ShippingAddress,
                    src.ShippingCity,
                    src.ShippingState,
                    src.ShippingCountry,
                    src.ShippingPostalCode)))
                .ForMember(dest => dest.DeliveryMethodId, opt => opt.Ignore()) // Set in service
                .ForMember(dest => dest.DeliveryMethod, opt => opt.Ignore()) // Set in service
                .ForMember(dest => dest.OrderItems, opt => opt.Ignore()) // Mapped separately
                .ForMember(dest => dest.Subtotal, opt => opt.Ignore()) // Calculated in service
                .ForMember(dest => dest.PaymentIntentId, opt => opt.Ignore()); // Set in service

            // conver from UpdateOrderDTO to Order
            //await _mapper.Map(updateOrderDTO, order);
          
            CreateMap<UpdateOrderDTO, Order>();
            
            // Mapping from Order to OrderToReturnDto with proper DeliveryMethod handling
            CreateMap<Order, OrderToReturnDto>()
                .ForMember(dest => dest.DeliveryMethod, opt => opt.MapFrom(src => src.DeliveryMethod != null ? src.DeliveryMethod.ShortName : "Standard"))
                .ForMember(dest => dest.ShippingPrice, opt => opt.MapFrom(src => src.DeliveryMethod != null ? src.DeliveryMethod.Cost : 0))
                .ForMember(dest => dest.Total, opt => opt.MapFrom(src => src.GetTotal()))
                .ForMember(dest => dest.CustomerEmail, opt => opt.MapFrom(src => src.Customer != null ? src.Customer.Email : null))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status.ToString()));
                
            CreateMap<OrderToReturnDto, Order>();
            CreateMap<OrderItem, OrderItemDto>().ReverseMap();
            CreateMap<Address, AddressDto>().ReverseMap();

        }
    }
}
