using AutoMapper;
using RedBubble.Application.DTOs.OrderItem;
using RedBubble.Domain.Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RedBubble.Application.Mappers
{
    public class OrderItemProfile : Profile
    {
        public OrderItemProfile() 
        {
            // conver from CreateOrderItemDTO to OrderItem
            CreateMap<CreateOrderItemDTO, OrderItem>()
                .ForMember(dest => dest.Id, opt => opt.Ignore()) // Generated by DB
                .ForMember(dest => dest.OrderId, opt => opt.Ignore()) // Set when saving
                .ForMember(dest => dest.Order, opt => opt.Ignore()) // Navigation property
                .ForMember(dest => dest.UnitPrice, opt => opt.Ignore())// Fetched from DB
                .ForMember(dest => dest.TotalPrice, opt => opt.Ignore()); // Fetched from DB
        }
    }
}
